# 定义端口
server:
  port:
    28205
  # 服务器URL
  url:
    http://localhost:28205

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hx_anime?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 自动建表
      ddl-auto: update
    show-sql: true
  web:
    resources:
      # 让服务器支持静态资源访问
      static-locations: classpath:/static/,file:D:/HX-ANiMe-File
  # 允许的最大上传文件大小
  multipart:
    max-file-size: 50MB
    max-request-size: 50MB

jwt:
  secret-key: "!@#$^HengXin%Loli0721_-"
  # 过期时间: (一天) | 单位: 毫秒
  expiration-time: 86400000

file:
  # 文件存储路径
  path: "D:/HX-ANiMe-File"